### ISSUE TITLE
Last line of selection doesn't come through

### ISSUE THREAD

**Issue by maikeldaloo** [ctruett/FeaturePresentation#4]
Hi there,

This is a great plugin, by the way, I've always wanted something like this for my editor - thanks for building this.

One minor issue I'm having is that the last line never comes through.
To test this, I made a selection that was a single line - and that line didn't come through, I got an empty new tab.

I'm on OS X El Capitan, using ST3.

**Comment by maikeldaloo** [comment]
Like I mentioned, this is a minor bug for me, I can get around it by selecting an extra line, but thought you should know about it.

**Comment by ctruett** [comment]
Hey, sorry that it has taken so long to get back to you. I'll check it out and see what's going on.

**Comment by LumberJaxolotl** [comment]
Sad to see this issue still open. this is super useful plugin in my opinion, and while it still works, it can be very annoying to have to remember to go to the next line after your selection in order to isolate the code. thank you good sir for making this but if you ever come back to this repository please, in the name  of everything holy, fix this for the 700+ people who are/have used this.

**Comment by ctruett** [comment]
This appears to be resolved with the changes I've just pulled in from another contributor. Sorry it has taken so long!
